# Generated by Django 4.2.1 on 2023-06-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
    ]
