# Generated by Django 4.2.1 on 2023-07-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSide', '0003_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
