# Generated by Django 4.2.1 on 2023-08-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSide', '0004_products_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
