# Generated by Django 4.2.1 on 2023-08-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSide', '0006_specification_products_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
