# Generated by Django 4.2.1 on 2023-09-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSide', '0007_alter_products_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='subcategory',
            field=models.CharField(default='', max_length=255),
        ),
    ]
